version: 1
appRoot: vdsc-react-app
frontend:
  phases:
    preBuild:
      commands:
        # Instala as dependências
        - npm ci
        
    build:
      commands:
        # Comando para gerar a pasta de produção
        - echo "Gerando build de produção..."
        - npm run build

    postBuild:
      commands:
        # Deploy para S3 no bucket específico por branch
        - echo "Iniciando deploy para S3..."
        - export BRANCH_NAME=${AWS_BRANCH}
        - aws s3 sync build/ s3://vdsc-prd-s3-videos/deploy/amplify/vdsc-web-app/${BRANCH_NAME}/ --delete --region us-east-1
        - echo "Deploy concluído com sucesso para branch ${BRANCH_NAME}!"

  artifacts:
    # Pasta onde o React gera os arquivos finais (geralmente 'build' ou 'dist' se usar Vite)
    baseDirectory: build
    files:
      - '**/*'

  cache:
    paths:
      - node_modules/**/*
